### ISSUE TITLE
Start server with correct arguments

### ISSUE THREAD

**Issue by bdw429s** [elpete/box-ngrok#1]
This line 
https://github.com/elpete/box-ngrok/blob/master/commands/server/share.cfc#L38
works fine for the default server, but if a specific server name, directory, or config file are passed in to the `server share` command, those need to be passed along to the `server start` command to ensure the correct server gets started.

**Comment by elpete** [comment]
Would something like this work?

``` cfc
var serverArgs = duplicate( arguments );
serverArgs.openBrowser = false;
command( "server start" )
    .params( argumentCollection = serverArgs )
    .run();
```

**Comment by bdw429s** [comment]
Yeah, that should work. The duplicate is probably unnecessary unless either command modifies the arguments. And the entire argument struct isn't necessary but the extras will just be ignored.

**Comment by bdw429s** [comment]
Thanks @elpete !
