### ISSUE TITLE
server share stop not stopping share

### ISSUE THREAD

**Issue by bdw429s** [elpete/box-ngrok#3]
If I start a server and then open a share like so it works great:
```
start
share
```
However if I run `server share stop`, the tunnel still passes through to my local server unabated and the `ngrok-windows.exe` process remains running.  Stopping the local server gives me a message about the tunnel not being found, but I'm still not sure if NGrok is really stopped since the `ngrok-windows.exe` process never dies until I kill it manually.

Is there any output from the ngrok command that we can output when stopping the tunnel to help debug?

**Comment by bdw429s** [comment]
I got a chance to poke at this tonight.  I can confirm that the `DELETE` request to stop the tunnel is correctly returning a `204` like it should and hitting the API to get a list of tunnels afterwards shows no tunnels are running.  I think this may be a bug in Ngrok.  The tunnels seem to just keep running until I kill the binary.

**Comment by elpete** [comment]
This happens on Mac as well. The difference is it doesn't seem like the Mac binary is blocking.

I'm not sure how to actually kill the binary. On either platform.

**Comment by bdw429s** [comment]
This thread seems to imply that the only way to stop the share is kill the process.
http://stackoverflow.com/questions/26291006/stop-sharing-a-port-on-ngrok

**Comment by elpete** [comment]
I would think Java would have a way to interact with the system processes? I can look in to that.

**Comment by bdw429s** [comment]
If I keep a reference to the `Process` returned by the `start()` method and I call `process.destroy()` on it, that will kill the ngrok binary.  Closing the CommandBox console will also kill it.  I assume because it's a child process.

**Comment by bdw429s** [comment]
See this here:
https://github.com/elpete/box-ngrok/pull/5
