### ISSUE TITLE
Doesn't bind when using local host other than localhost

### ISSUE THREAD

**Issue by bdw429s** [elpete/box-ngrok#7]
Need to specify the host as well as the IP so this can work with the hostupdater module which doesn't bind your local sites to `127.0.0.1`.

**Comment by bdw429s** [comment]
Fixed in this commit: https://github.com/elpete/box-ngrok/commit/22130be76e79adb4870a9526112e160fe62322d6

@elpete please bump the version and re-publish to forgebox and close this ticket.

**Comment by elpete** [comment]
Version 1.3.0 pushed.
